[build-system]
requires = [
    "setuptools",
    "setuptools_scm[toml]",
    "wheel"
]
build-backend = 'setuptools.build_meta'

# requires-python = ">= 3.9"
[project]
requires-python = ">= 3.9"
name = "saber-bip"
description = "Parse Narrow-scope VITA 49.2 Data"

version = "0.1.2-c"
dependencies = [
    "numpy>=2.0.0",
    "pandas",
    "pyarrow>=17.0.0",
    "tqdm",
    "numba"
]

[project.optional-dependencies]
test = [
    "pytest"
]

[project.scripts]
bip = "bip.cli:main"

[tool.poetry]
name = "saber-bip"
packages = [
    { include = "bip", from = "src", to = "saber-bip" }
]

[tool.pytest.ini_options]
pythonpath = [
    ".", "src"
]

testpaths = [
    "tests"
]