name: RF Data Pipeline Pytest

on: 
  push:

jobs:
  pytest:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5.1.0
        with: 
          python-version: "3.12.4"

      - name: Install dependencies
        run: |
          pip install pytest pytest-cov
          pip install .

      - name: pytest
        run: |
          pytest -vv --cov=. tests > pytest-coverage.txt
      
